using System.Collections.Generic;

namespace EasySQL
{
    /// <summary>
    /// PostgreSQL 数据库方言实现。
    /// </summary>
    public class PostgreSQLDialect:SQLDialectBase
    {
        static readonly IDbFunction dbFunc = new PostgreSQLFunctions();

        /// <inheritdoc/>
        public override DialectType DialectType => DialectType.PostgreSQL;

        /// <inheritdoc/>
        public override string DialectName { get { return "PostgreSQL"; } }

        /// <inheritdoc/>
        public override IDbFunction Func { get { return dbFunc; } }

        /// <inheritdoc/>
        public override bool IsBracketJoin => false;

        /// <inheritdoc/>
        protected override string QuoteKeyWord(string word)
        {
            return $"\"{word}\"";
        }

        /// <inheritdoc/>
        public override bool IsKeyWord(string word)
        {
            return keyWords.Contains(word.ToUpper());
        }
        static readonly List<string> keyWords = new List<string>() { "ABS", "ABSENT", "ACCORDING", "ADA", "ALL", "ALLOCATE", "ANALYSE", "ANALYZE", "AND", "ANY", "ARE", "ARRAY", "ARRAY_AGG", "ARRAY_MAX_CARDINALITY", "AS", "ASC", "ASENSITIVE", "ASYMMETRIC", "ATOMIC", "ATTRIBUTES", "AUTHORIZATION", "AVG", "BASE64", "BEGIN_FRAME", "BEGIN_PARTITION", "BERNOULLI", "BINARY", "BIT_LENGTH", "BLOB", "BLOCKED", "BOM", "BOTH", "BREADTH", "CALL", "CARDINALITY", "CASE", "CAST", "CATALOG_NAME", "CEIL", "CEILING", "CHARACTERS", "CHARACTER_LENGTH", "CHARACTER_SET_CATALOG", "CHARACTER_SET_NAME", "CHARACTER_SET_SCHEMA", "CHAR_LENGTH", "CHECK", "CLASS_ORIGIN", "CLOB", "COBOL", "COLLATE", "COLLATION", "COLLATION_CATALOG", "COLLATION_NAME", "COLLATION_SCHEMA", "COLLECT", "COLUMN", "COLUMNS", "COLUMN_NAME", "COMMAND_FUNCTION", "COMMAND_FUNCTION_CODE", "CONCURRENTLY", "CONDITION", "CONDITION_NUMBER", "CONNECT", "CONNECTION_NAME", "CONSTRAINT", "CONSTRAINT_CATALOG", "CONSTRAINT_NAME", "CONSTRAINT_SCHEMA", "CONSTRUCTOR", "CONTAINS", "CONTROL", "CONVERT", "CORR", "CORRESPONDING", "COUNT", "COVAR_POP", "COVAR_SAMP", "CREATE", "CROSS", "CUBE", "CUME_DIST", "CURRENT_CATALOG", "CURRENT_DATE", "CURRENT_DEFAULT_TRANSFORM_GROUP", "CURRENT_PATH", "CURRENT_ROLE", "CURRENT_ROW", "CURRENT_SCHEMA", "CURRENT_TIME", "CURRENT_TIMESTAMP", "CURRENT_TRANSFORM_GROUP_FOR_TYPE", "CURRENT_USER", "CURSOR_NAME", "DATALINK", "DATE", "DATETIME_INTERVAL_CODE", "DATETIME_INTERVAL_PRECISION", "DB", "DEFAULT", "DEFERRABLE", "DEFINED", "DEGREE", "DENSE_RANK", "DEPTH", "DEREF", "DERIVED", "DESC", "DESCRIBE", "DESCRIPTOR", "DETERMINISTIC", "DIAGNOSTICS", "DISCONNECT", "DISPATCH", "DISTINCT", "DLNEWCOPY", "DLPREVIOUSCOPY", "DLURLCOMPLETE", "DLURLCOMPLETEONLY", "DLURLCOMPLETEWRITE", "DLURLPATH", "DLURLPATHONLY", "DLURLPATHWRITE", "DLURLSCHEME", "DLURLSERVER", "DLVALUE", "DO", "DYNAMIC", "DYNAMIC_FUNCTION", "DYNAMIC_FUNCTION_CODE", "ELEMENT", "ELSE", "EMPTY", "END", "END-EXEC", "END_FRAME", "END_PARTITION", "ENFORCED", "EQUALS", "EVERY", "EXCEPT", "EXCEPTION", "EXEC", "EXP", "EXPRESSION", "FALSE", "FETCH", "FILE", "FINAL", "FIRST_VALUE", "FLAG", "FLOOR", "FOR", "FOREIGN", "FORTRAN", "FOUND", "FRAME_ROW", "FREE", "FREEZE", "FROM", "FS", "FULL", "FUSION", "GENERAL", "GENERATED", "GET", "GO", "GOTO", "GRANT", "GROUP", "GROUPING", "GROUPS", "HAVING", "HEX", "HIERARCHY", "IGNORE", "ILIKE", "IMMEDIATELY", "IMPLEMENTATION", "IMPORT", "IN", "INDENT", "INDICATOR", "INITIALLY", "INNER", "INSTANCE", "INSTANTIABLE", "INTEGRITY", "INTERSECT", "INTERSECTION", "INTO", "IS", "ISNULL", "JOIN", "KEY_MEMBER", "KEY_TYPE", "LAG", "LAST_VALUE", "LATERAL", "LEAD", "LEADING", "LEFT", "LENGTH", "LIBRARY", "LIKE", "LIKE_REGEX", "LIMIT", "LINK", "LN", "LOCALTIME", "LOCALTIMESTAMP", "LOCATOR", "LOWER", "MAP", "MATCHED", "MAX", "MAX_CARDINALITY", "MEMBER", "MERGE", "MESSAGE_LENGTH", "MESSAGE_OCTET_LENGTH", "MESSAGE_TEXT", "METHOD", "MIN", "MOD", "MODIFIES", "MODULE", "MORE", "MULTISET", "MUMPS", "NAMESPACE", "NATURAL", "NCLOB", "NESTING", "NEW", "NFC", "NFD", "NFKC", "NFKD", "NIL", "NORMALIZE", "NORMALIZED", "NOT", "NOTNULL", "NTH_VALUE", "NTILE", "NULL", "NULLABLE", "NUMBER", "OCCURRENCES_REGEX", "OCTETS", "OCTET_LENGTH", "OFFSET", "OLD", "ON", "ONLY", "OPEN", "OR", "ORDER", "ORDERING", "OTHERS", "OUTER", "OUTPUT", "OVERLAPS", "OVERRIDING", "PAD", "PARAMETER", "PARAMETER_MODE", "PARAMETER_NAME", "PARAMETER_ORDINAL_POSITION", "PARAMETER_SPECIFIC_CATALOG", "PARAMETER_SPECIFIC_NAME", "PARAMETER_SPECIFIC_SCHEMA", "PASCAL", "PASSTHROUGH", "PATH", "PERCENT", "PERCENTILE_CONT", "PERCENTILE_DISC", "PERCENT_RANK", "PERIOD", "PERMISSION", "PLACING", "PLI", "PORTION", "POSITION_REGEX", "POWER", "PRECEDES", "PRIMARY", "PUBLIC", "RANK", "READS", "RECOVERY", "REFERENCES", "REFERENCING", "REGR_AVGX", "REGR_AVGY", "REGR_COUNT", "REGR_INTERCEPT", "REGR_R2", "REGR_SLOPE", "REGR_SXX", "REGR_SXY", "REGR_SYY", "REQUIRING", "RESPECT", "RESTORE", "RESULT", "RETURN", "RETURNED_CARDINALITY", "RETURNED_LENGTH", "RETURNED_OCTET_LENGTH", "RETURNED_SQLSTATE", "RETURNING", "RIGHT", "ROLLUP", "ROUTINE", "ROUTINE_CATALOG", "ROUTINE_NAME", "ROUTINE_SCHEMA", "ROW_COUNT", "ROW_NUMBER", "SCALE", "SCHEMA_NAME", "SCOPE", "SCOPE_CATALOG", "SCOPE_NAME", "SCOPE_SCHEMA", "SECTION", "SELECT", "SELECTIVE", "SELF", "SENSITIVE", "SERVER_NAME", "SESSION_USER", "SETS", "SIMILAR", "SIZE", "SOME", "SOURCE", "SPACE", "SPECIFIC", "SPECIFICTYPE", "SPECIFIC_NAME", "SQL", "SQLCODE", "SQLERROR", "SQLEXCEPTION", "SQLSTATE", "SQLWARNING", "SQRT", "STATE", "STATIC", "STDDEV_POP", "STDDEV_SAMP", "STRUCTURE", "STYLE", "SUBCLASS_ORIGIN", "SUBMULTISET", "SUBSTRING_REGEX", "SUCCEEDS", "SUM", "SYMMETRIC", "SYSTEM_TIME", "SYSTEM_USER", "TABLE", "TABLESAMPLE", "TABLE_NAME", "THEN", "TIES", "TIMEZONE_HOUR", "TIMEZONE_MINUTE", "TO", "TOKEN", "TOP_LEVEL_COUNT", "TRAILING", "TRANSACTIONS_COMMITTED", "TRANSACTIONS_ROLLED_BACK", "TRANSACTION_ACTIVE", "TRANSFORM", "TRANSFORMS", "TRANSLATE", "TRANSLATE_REGEX", "TRANSLATION", "TRIGGER_CATALOG", "TRIGGER_NAME", "TRIGGER_SCHEMA", "TRIM_ARRAY", "TRUE", "UESCAPE", "UNDER", "UNION", "UNIQUE", "UNLINK", "UNNAMED", "UNNEST", "UNTYPED", "UPPER", "URI", "USAGE", "USER", "USER_DEFINED_TYPE_CATALOG", "USER_DEFINED_TYPE_CODE", "USER_DEFINED_TYPE_NAME", "USER_DEFINED_TYPE_SCHEMA", "USING", "VALUE_OF", "VARBINARY", "VARIADIC", "VAR_POP", "VAR_SAMP", "VERBOSE", "VERSIONING", "WHEN", "WHENEVER", "WHERE", "WIDTH_BUCKET", "WINDOW", "WITH", "XMLAGG", "XMLBINARY", "XMLCAST", "XMLCOMMENT", "XMLDECLARATION", "XMLDOCUMENT", "XMLITERATE", "XMLNAMESPACES", "XMLQUERY", "XMLSCHEMA", "XMLTABLE", "XMLTEXT", "XMLVALIDATE",};
    }
}
